dist: trusty
sudo: false
language: python
python:
  - "3.6"
install:
  - pip3 install -e web
  - pip3 install pytest-cov
  - pip3 install coveralls
script:
  - pytest --cov web
after_success:
  - coveralls
