TextInputRequired = 'This field is required.'
TextUserAlreadyLoggedIn = 'You have already logged in.'
TextUserWrongPassword = 'Incorrect combination of username and password.'
TextUserLoginSuccess = 'Successfully logged in.'
TextPasswordMismatch = 'Passwords must match.'
TextUserUsernameOccupied = 'The username has been occupied. Please try another one.'
TextUserRegisterSuccess = 'Successfully registered.'
TextUserLogout = 'You have logged out.'
